### ISSUE TITLE
feature request: add option to have another interface on the nginx container instead of using host

### ISSUE THREAD

**Issue by brianhenson** [bmullan/ciab-remote-desktop#1]
First great scripts, it has already saved me a bunch of time. Could you please add a choice between using the hosts ports and adding another bridge to the local network so the container could get its own IP? It would make it where you could have a local web server on the host to control the devices among other features.

**Comment by bmullan** [comment]
@brianhenson thanks for trying out the CIAB remote desktop scripts.   Yeah, I tried to make it as simple to install as possible.   Once initially installed its also really easy to add additonal CNx desktop containers since you can just use LXD to copy/clone the initial CN1 container as many times as you want... then add additional user accounts to each of those, then go into Guacamole and do the same as well as new "connections" to each of the additonal container(s).

As to you suggestion.   Once you have CIAB installed on a VM or a fresh Server/Host you can do what you suggest yourself if you have a use-case requiring that configuration ?

You "could" just manually create another LXD container on that Host/Server though (not cloning either ciab-guac or CN1 container).

$ lxc launch ubuntu:bionic <cn_name>

Then install whatever your "local web server to control devices among other features" into that container.
Finally, you can then use LXD's Device Map capability to map a Host/Server Port to that new container

**examples:**

**lxc config device add new_cn_name proxyport80 proxy listen=tcp:0.0.0.0:80 connect=tcp:localhost:80**

would let you point a browser at your Host's IP address & port 80 but would connect to your **new_cn_name** Port 80

Note:  you can use whatever alias you want instead of "proxyport80"  as that is just an alias.
           And you could use any port you want you don't have to use 80 since you could point your
           Browser to that port and it could goto the new_ cn_name Port you choose.

**examples:**

**lxc config device add new_cn_name proxyport8000 proxy listen=tcp:0.0.0.0:8000 connect=tcp:localhost:80**

the above would map the Host's Port 8000 to the container's Port 80

so using the following in your browser would connect you to Port 80 in the container and whatever webserver is on that Port in the container.

**http://<host IP address>:8000**

**Why am i suggesting this approach?**  
Here are several good reasons in my opinion...

1. you can then clone/copy your new web server container to a different server running LXD and immediately be able to use that webserver there.

2. you can very easily snapshot your new web server container
 
3. the new container would be on the SAME IP subnet (usually 10.x.x.x) as all your other LXD containers and thus reachable to/from any of those.
 
4. the new container would be on the SAME IP subnet (usually 10.x.x.x) which is Isolated from general connections from the Internet but the new container still has access "out" to the internet just as the other LXD containers do.

**Comment by brianhenson** [comment]
True, I guess I am just not a fan of having the LXD Host server exposed to the internet even with the proxyport. I prefer to keep the server as clean as I can for when I scan it with vulnerability management software its like a black hole of sorts. Still great scripts though. I have it running with 4 CN containers right now with the nginx reverse proxy running the connections
